name: Cache Demo Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 🪣 Step: cache dependencies
      - name: prime-cache-47e4e4c
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-47e4e4c

      # 🧠 Step: echo cache result (hit or miss)
      - name: Echo cache result
        run: echo "Cache hit:${{ steps.cache.outputs.cache-hit }}"
