name: Cache Demo Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: prime-cache-47e4e4c
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-47e4e4c

      - name: Check cache result
        run: echo "Cache hit: ${{ steps.cache.outputs.cache-hit }}"

      - name: Install dependencies
        run: |
          pip install numpy
